### ISSUE TITLE
PyQt5

### ISSUE THREAD

**Issue by halbmy** [frodo4fingers/gimod#1]
Great project, Friedrich! Look forward to watch it growing and to use it eventually.
Support for PyQt5 would be great as many installers like WinPython come with QT5 instead of QT4.
Thomas

**Comment by frodo4fingers** [comment]
Thanks :-)
I just looked into Qt5 and it seems not to be a big problem. Will do that today!

Friedrich

**Comment by frodo4fingers** [comment]
I think that will do it.
