### ISSUE TITLE
replace icons svg with png

### ISSUE THREAD

**Issue by frodo4fingers** [frodo4fingers/gimod#2]
with that i can use the icons for better function description in the wiki

**Comment by florian-wagner** [comment]
Hey Friedrich,

sehr cooles Projekt! Ich teste bei Gelegenheit noch etwas ausführlicher. SVGs mit PNGs ersetzen ist aber nicht nötig, SVG ist fully webcompatible.

<img src="http://www.pygimli.org/_static/gimli_logo.svg" width="100%">

Schönes WE & beste Grüße
Florian

**Comment by frodo4fingers** [comment]
Ahoi

Nach dem, was ich gelesen und getestet habe, kann GitHub die SVGs nicht grafisch umsetzen, weil das wohl seitenintern zu Fehlern führt. Für das wiki wären die allerdings sehr praktisch.

Auf die Ergebnisse des auführlichen Testens bin ich sehr gespannt!

Schöne Grüße
Friedrich

**Comment by florian-wagner** [comment]
Hey Friedrich, 

ich hatte bisher noch keine Probleme. Das Bild oben habe ich einfach mit 

``` html
<img src="http://www.pygimli.org/_static/gimli_logo.svg" width="100%">
```

eingefügt. Wenn es hier in den issues und in den Readmes klappt, sollte es auch im Wiki funktionieren.

Beste Grüße
Florian

**Comment by frodo4fingers** [comment]
Hi,

ja, ich finde auch, dass es das sollte, aber tut es dann doch nicht. Ich habe mehrere Stile ausprobiert, die scheiterten. Bei der Recherche habe ich noch andere gefunden, die über das selbe Problem stolpern. Ich werde mich mal mit den GitHub-Pages auseinandersetzen und erstmal fix ein TeX aufsetzen...

**Comment by florian-wagner** [comment]
Hm okay, schade. Ja GitHub-Pages ist eine Möglichkeit. Aber für Python-Projekte ist eigl. sphinx das Dokumentations-Tool schlechthin. Damit ist sogar Python selber dokumentiert. readthedocs ist dann sowas wie ein GitHub-Pages für sphinx. Du schreibst also Deine Dokumentation als markdown oder reststructured text und readthedocs baut diese bei jedem commit neu und macht auch eine API dokumentation neuer funktionen oder so. Der Vorteil ist, dass Du Dich nicht auf ein Output-Format festlegst und jeder User selbst entscheidet ob er sich durch die HTML klickt, das PDF druckt, oder ein ebook runderlädt. Lohnt sich bestimmt auch mal da reinzuschauen:

https://docs.readthedocs.io/en/latest/getting_started.html

LG

**Comment by frodo4fingers** [comment]
Das sieht ziemlich gut und praktisch aus... momentan krieg ichs noch nicht zum laufen.

**Comment by frodo4fingers** [comment]
Anscheinend liegt das nicht-einbinden-können von github SVGs tatsächlich an github.. irgendwie. Über [rawgit](https://rawgit.com/) wird entsprechender Inhalt vorher verwertet. Naja. Das readthedocs gefällt mir nun ganz gut, sodass ich das wiki demnächst ersetzen werde.

Danke für den Tipp!!
